repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=120]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'PYTHONPATH=$PWD pylint "$@"' --
        language: system
        types: [python]
        require_serial: false
        args: [--rcfile=.pylintrc]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional, --explicit-package-bases]
        additional_dependencies: [types-requests]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        args: [--fix]
