repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'PYTHONPATH=$PWD pylint "$@"' --
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'PYTHONPATH=$PWD mypy "$@"' --
        language: system
        types: [python]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        args: [--fix]
